# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        swift --version
        swift test
    - name: Danger
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        brew install danger/tap/danger-swift
        cd Danger
        swift run danger-swift ci --cwd ../
